[package]
name = "copy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "copy-A"
path = "src/A.rs"

[[bin]]
name = "copy-B"
path = "src/B.rs"

[[bin]]
name = "copy-C"
path = "src/C.rs"

[[bin]]
name = "copy-memory"
path = "src/memory.rs"

[dependencies]
sv-lib = { path = "../../sv-lib" }
clap = { version = "4.5", features = ["derive"] }
