# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/AlgorithmDataFlowGraph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/AlgorithmDataFlowGraph.proto',
  package='ss.sylva.sdf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"proto/AlgorithmDataFlowGraph.proto\x12\x0css.sylva.sdf\"c\n\x16\x41lgorithmDataFlowGraph\x12&\n\x08vertices\x18\x01 \x03(\x0b\x32\x14.ss.sylva.sdf.Vertex\x12!\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x12.ss.sylva.sdf.Edge\"u\n\x06Vertex\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x66unc\x18\x02 \x01(\t\x12\'\n\x0binput_ports\x18\x03 \x03(\x0b\x32\x12.ss.sylva.sdf.Port\x12(\n\x0coutput_ports\x18\x04 \x03(\x0b\x32\x12.ss.sylva.sdf.Port\"V\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06src_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x64st_id\x18\x03 \x01(\x05\x12\x10\n\x08src_port\x18\x04 \x01(\t\x12\x10\n\x08\x64st_port\x18\x05 \x01(\t\".\n\x04Port\x12\x12\n\ntoken_rate\x18\x01 \x01(\x05\x12\x12\n\ntoken_size\x18\x02 \x01(\x05\x62\x06proto3'
)




_ALGORITHMDATAFLOWGRAPH = _descriptor.Descriptor(
  name='AlgorithmDataFlowGraph',
  full_name='ss.sylva.sdf.AlgorithmDataFlowGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='ss.sylva.sdf.AlgorithmDataFlowGraph.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='ss.sylva.sdf.AlgorithmDataFlowGraph.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=151,
)


_VERTEX = _descriptor.Descriptor(
  name='Vertex',
  full_name='ss.sylva.sdf.Vertex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ss.sylva.sdf.Vertex.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='func', full_name='ss.sylva.sdf.Vertex.func', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_ports', full_name='ss.sylva.sdf.Vertex.input_ports', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_ports', full_name='ss.sylva.sdf.Vertex.output_ports', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=270,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='ss.sylva.sdf.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ss.sylva.sdf.Edge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_id', full_name='ss.sylva.sdf.Edge.src_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_id', full_name='ss.sylva.sdf.Edge.dst_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='ss.sylva.sdf.Edge.src_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='ss.sylva.sdf.Edge.dst_port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=358,
)


_PORT = _descriptor.Descriptor(
  name='Port',
  full_name='ss.sylva.sdf.Port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_rate', full_name='ss.sylva.sdf.Port.token_rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_size', full_name='ss.sylva.sdf.Port.token_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=406,
)

_ALGORITHMDATAFLOWGRAPH.fields_by_name['vertices'].message_type = _VERTEX
_ALGORITHMDATAFLOWGRAPH.fields_by_name['edges'].message_type = _EDGE
_VERTEX.fields_by_name['input_ports'].message_type = _PORT
_VERTEX.fields_by_name['output_ports'].message_type = _PORT
DESCRIPTOR.message_types_by_name['AlgorithmDataFlowGraph'] = _ALGORITHMDATAFLOWGRAPH
DESCRIPTOR.message_types_by_name['Vertex'] = _VERTEX
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Port'] = _PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlgorithmDataFlowGraph = _reflection.GeneratedProtocolMessageType('AlgorithmDataFlowGraph', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMDATAFLOWGRAPH,
  '__module__' : 'proto.AlgorithmDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.sdf.AlgorithmDataFlowGraph)
  })
_sym_db.RegisterMessage(AlgorithmDataFlowGraph)

Vertex = _reflection.GeneratedProtocolMessageType('Vertex', (_message.Message,), {
  'DESCRIPTOR' : _VERTEX,
  '__module__' : 'proto.AlgorithmDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.sdf.Vertex)
  })
_sym_db.RegisterMessage(Vertex)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
  'DESCRIPTOR' : _EDGE,
  '__module__' : 'proto.AlgorithmDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.sdf.Edge)
  })
_sym_db.RegisterMessage(Edge)

Port = _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {
  'DESCRIPTOR' : _PORT,
  '__module__' : 'proto.AlgorithmDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.sdf.Port)
  })
_sym_db.RegisterMessage(Port)


# @@protoc_insertion_point(module_scope)
