[package]
name = "sv-test"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "A"
path = "minimum/A.rs"

[[bin]]
name = "B"
path = "minimum/B.rs"

[[bin]]
name = "C"
path = "minimum/C.rs"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4", features = ["derive"] }
