[package]
name = "lenet5"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lenet5-load-input"
path = "src/load-input.rs"

[[bin]]
name = "lenet5-conv"
path = "src/conv.rs"

[[bin]]
name = "lenet5-pooling"
path = "src/pooling.rs"

[[bin]]
name = "lenet5-reshape"
path = "src/reshape.rs"

[[bin]]
name = "lenet5-fc"
path = "src/fc.rs"

[[bin]]
name = "lenet5-store-output"
path = "src/store-output.rs"

[[bin]]
name = "lenet5-memory"
path = "src/memory.rs"

[dependencies]
sv-lib = { path = "../../sv-lib" }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4" 
byteorder = "1.5.0"
ndarray = "0.15"
