[package]
name = "sobel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "copy-load"
path = "src/load.rs"

[[bin]]
name = "copy-copy"
path = "src/copy.rs"

[[bin]]
name = "copy-gx"
path = "src/gx.rs"

[[bin]]
name = "copy-gy"
path = "src/gy.rs"

[[bin]]
name = "copy-combine"
path = "src/combine.rs"

[[bin]]
name = "copy-store"
path = "src/store.rs"

[[bin]]
name = "copy-convert"
path = "src/convert.rs"

[[bin]]
name = "copy-memory"
path = "src/memory.rs"

[dependencies]
sv-lib = { path = "../../sv-lib" }
clap = { version = "4.5", features = ["derive"] }
