syntax = "proto3";

package ss.sylva.ds.alimplib;

message AlimpLib {
  string name = 1;
  string version = 2;
  string author = 3;
  string description = 4;
  repeated Algorithm algorithms = 5;
}

message Algorithm {
  string func = 1;
  string description = 2;
  repeated Parameter parameters = 3;
  repeated Implementation implementations = 4;
}

message Parameter {
  string name = 1;
  int32 value = 2;
  string description = 3;
}

message Implementation {
  string location = 1;
  string area = 2;
  string latency = 3;
  string power = 4;
  repeated DataChunk input_pattern = 5;
  repeated DataChunk output_pattern = 6;
}

message DataChunk {
  int32 time = 1;
  int32 addr = 2;
}
