# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Floorplan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/Floorplan.proto',
  package='ss_floorplan',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/Floorplan.proto\x12\x0css_floorplan\"\x99\x01\n\tFloorplan\x12\x11\n\tmax_width\x18\x01 \x01(\x05\x12\x12\n\nmax_height\x18\x02 \x01(\x05\x12*\n\x03pos\x18\x03 \x03(\x0b\x32\x1d.ss_floorplan.RectanglePosion\x12+\n\x05shape\x18\x04 \x03(\x0b\x32\x1c.ss_floorplan.RectangleShape\x12\x0c\n\x04\x63onn\x18\x05 \x03(\x05\"\'\n\x0fRectanglePosion\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"/\n\x0eRectangleShape\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x62\x06proto3'
)




_FLOORPLAN = _descriptor.Descriptor(
  name='Floorplan',
  full_name='ss_floorplan.Floorplan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_width', full_name='ss_floorplan.Floorplan.max_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_height', full_name='ss_floorplan.Floorplan.max_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='ss_floorplan.Floorplan.pos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='ss_floorplan.Floorplan.shape', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conn', full_name='ss_floorplan.Floorplan.conn', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=193,
)


_RECTANGLEPOSION = _descriptor.Descriptor(
  name='RectanglePosion',
  full_name='ss_floorplan.RectanglePosion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ss_floorplan.RectanglePosion.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ss_floorplan.RectanglePosion.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=234,
)


_RECTANGLESHAPE = _descriptor.Descriptor(
  name='RectangleShape',
  full_name='ss_floorplan.RectangleShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ss_floorplan.RectangleShape.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='ss_floorplan.RectangleShape.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=283,
)

_FLOORPLAN.fields_by_name['pos'].message_type = _RECTANGLEPOSION
_FLOORPLAN.fields_by_name['shape'].message_type = _RECTANGLESHAPE
DESCRIPTOR.message_types_by_name['Floorplan'] = _FLOORPLAN
DESCRIPTOR.message_types_by_name['RectanglePosion'] = _RECTANGLEPOSION
DESCRIPTOR.message_types_by_name['RectangleShape'] = _RECTANGLESHAPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Floorplan = _reflection.GeneratedProtocolMessageType('Floorplan', (_message.Message,), {
  'DESCRIPTOR' : _FLOORPLAN,
  '__module__' : 'proto.Floorplan_pb2'
  # @@protoc_insertion_point(class_scope:ss_floorplan.Floorplan)
  })
_sym_db.RegisterMessage(Floorplan)

RectanglePosion = _reflection.GeneratedProtocolMessageType('RectanglePosion', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLEPOSION,
  '__module__' : 'proto.Floorplan_pb2'
  # @@protoc_insertion_point(class_scope:ss_floorplan.RectanglePosion)
  })
_sym_db.RegisterMessage(RectanglePosion)

RectangleShape = _reflection.GeneratedProtocolMessageType('RectangleShape', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLESHAPE,
  '__module__' : 'proto.Floorplan_pb2'
  # @@protoc_insertion_point(class_scope:ss_floorplan.RectangleShape)
  })
_sym_db.RegisterMessage(RectangleShape)


# @@protoc_insertion_point(module_scope)
