# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ImplementationDataFlowGraph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import AlimpLib_pb2 as proto_dot_AlimpLib__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ImplementationDataFlowGraph.proto',
  package='ss.sylva.ds.sdf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'proto/ImplementationDataFlowGraph.proto\x12\x0fss.sylva.ds.sdf\x1a\x14proto/AlimpLib.proto\"n\n\x1bImplementationDataFlowGraph\x12)\n\x08vertices\x18\x01 \x03(\x0b\x32\x17.ss.sylva.ds.sdf.Vertex\x12$\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x15.ss.sylva.ds.sdf.Edge\"\x8d\x01\n\x06Vertex\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x66unc\x18\x02 \x01(\t\x12\x10\n\x08instance\x18\x03 \x01(\t\x12*\n\x0binput_ports\x18\x04 \x03(\x0b\x32\x15.ss.sylva.ds.sdf.Port\x12+\n\x0coutput_ports\x18\x05 \x03(\x0b\x32\x15.ss.sylva.ds.sdf.Port\"V\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06src_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x64st_id\x18\x03 \x01(\x05\x12\x10\n\x08src_port\x18\x04 \x01(\t\x12\x10\n\x08\x64st_port\x18\x05 \x01(\t\"<\n\x04Port\x12\x34\n\x0b\x64\x61ta_chunks\x18\x01 \x03(\x0b\x32\x1f.ss.sylva.ds.alimplib.DataChunkb\x06proto3'
  ,
  dependencies=[proto_dot_AlimpLib__pb2.DESCRIPTOR,])




_IMPLEMENTATIONDATAFLOWGRAPH = _descriptor.Descriptor(
  name='ImplementationDataFlowGraph',
  full_name='ss.sylva.ds.sdf.ImplementationDataFlowGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='ss.sylva.ds.sdf.ImplementationDataFlowGraph.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='ss.sylva.ds.sdf.ImplementationDataFlowGraph.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=192,
)


_VERTEX = _descriptor.Descriptor(
  name='Vertex',
  full_name='ss.sylva.ds.sdf.Vertex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ss.sylva.ds.sdf.Vertex.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='func', full_name='ss.sylva.ds.sdf.Vertex.func', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance', full_name='ss.sylva.ds.sdf.Vertex.instance', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_ports', full_name='ss.sylva.ds.sdf.Vertex.input_ports', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_ports', full_name='ss.sylva.ds.sdf.Vertex.output_ports', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=336,
)


_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='ss.sylva.ds.sdf.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ss.sylva.ds.sdf.Edge.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_id', full_name='ss.sylva.ds.sdf.Edge.src_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_id', full_name='ss.sylva.ds.sdf.Edge.dst_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='ss.sylva.ds.sdf.Edge.src_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='ss.sylva.ds.sdf.Edge.dst_port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=424,
)


_PORT = _descriptor.Descriptor(
  name='Port',
  full_name='ss.sylva.ds.sdf.Port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_chunks', full_name='ss.sylva.ds.sdf.Port.data_chunks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=486,
)

_IMPLEMENTATIONDATAFLOWGRAPH.fields_by_name['vertices'].message_type = _VERTEX
_IMPLEMENTATIONDATAFLOWGRAPH.fields_by_name['edges'].message_type = _EDGE
_VERTEX.fields_by_name['input_ports'].message_type = _PORT
_VERTEX.fields_by_name['output_ports'].message_type = _PORT
_PORT.fields_by_name['data_chunks'].message_type = proto_dot_AlimpLib__pb2._DATACHUNK
DESCRIPTOR.message_types_by_name['ImplementationDataFlowGraph'] = _IMPLEMENTATIONDATAFLOWGRAPH
DESCRIPTOR.message_types_by_name['Vertex'] = _VERTEX
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Port'] = _PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImplementationDataFlowGraph = _reflection.GeneratedProtocolMessageType('ImplementationDataFlowGraph', (_message.Message,), {
  'DESCRIPTOR' : _IMPLEMENTATIONDATAFLOWGRAPH,
  '__module__' : 'proto.ImplementationDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.ds.sdf.ImplementationDataFlowGraph)
  })
_sym_db.RegisterMessage(ImplementationDataFlowGraph)

Vertex = _reflection.GeneratedProtocolMessageType('Vertex', (_message.Message,), {
  'DESCRIPTOR' : _VERTEX,
  '__module__' : 'proto.ImplementationDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.ds.sdf.Vertex)
  })
_sym_db.RegisterMessage(Vertex)

Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
  'DESCRIPTOR' : _EDGE,
  '__module__' : 'proto.ImplementationDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.ds.sdf.Edge)
  })
_sym_db.RegisterMessage(Edge)

Port = _reflection.GeneratedProtocolMessageType('Port', (_message.Message,), {
  'DESCRIPTOR' : _PORT,
  '__module__' : 'proto.ImplementationDataFlowGraph_pb2'
  # @@protoc_insertion_point(class_scope:ss.sylva.ds.sdf.Port)
  })
_sym_db.RegisterMessage(Port)


# @@protoc_insertion_point(module_scope)
